# 게임에서 사용할 캐릭터를 정의합니다.
define USER = Character('김 한', color="#c8ffc8")
define DAV = Character('디아블로', color= "#551313")
define AL = Character('알리', color= "#5a5c07")
define ALA = Character('알레아', color= "#f5e50cff")
define JAN = Character('잔', color= "#a05111")
define MA = Character('마튼', color= "#42ebe2")
define ETC = Character('병사', color= "#fffefe")
define G = Character('교황', color= "#530202")
define BA = Character('바륵', color= "#530202")
define J = Character('재운', color= "#c0c2ad")
define MS  = Character('미셸', color= "#008bfd")
define MEKIA = Character('메키아', color= "#cc02ff")
define LIL = Character('릴리스', color= "#681818")
define HAN = Character('한', color= "#851a1a")
define KEN = Character('자켄', color= "#792121")
define NABE = Character('나베리우스', color= "#691e1e")
define AGARES = Character('아가레스', color= "#abe77a")
define ETC1 = Character('마족들', color= "#fcfcfc")
define MU = Character('무르무르', color= "#0ff8d1")
define MAHA = Character('마하', color= "#084663")
define ETR2 = Character('엘프1', color= "#25d373")
define KAR = Character('카르', color= "#086e2a")
define ETC3 = Character('종업원', color= "#f8f7f7")
define ETC4 = Character('경비병1', color= "#fdfdfd")
define RIN = Character('쟈린', color= "#e4b3b3")
define MERHAN = Character('메르한', color= "#8badc9")
define PENRI = Character('펜리', color= "#cfcfbecb")
define GORREM = Character('골렘', color= "#8d6853fa")
define NARR = Character('나레이션', color= "#10942c")
define SYSTEM = Character('시스템', color= "#ffffff")
define ETC5 = Character('마족', color= "#fcfcfc")

#144